In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib

Using matplotlib backend: Qt5Agg

In [2]:
all_data = pd.read_csv("Desktop/Project/2021 Project/UI/Xtiana/Tiana_Data.csv")
all_data.head(5)

,Diets,Week_1_Mean_Weight,Week_2_Mean_Weight,Week_3_Mean_Weight,Week_4_Mean_Weight,Week_5_Mean_Weight,Week_6_Mean_Weight,Week_7_Mean_Weight,Week_8_Mean_Weight,Week_9_Mean_Weight,...,Week_3_Mean_Length,Week_4_Mean_Length,Week_5_Mean_Length,Week_6_Mean_Length,Week_7_Mean_Length,Week_8_Mean_Length,Week_9_Mean_Length,Week_10_Mean_Length,Week_11_Mean_Length,Week_12_Mean_Length
0,Diet_A,1.50,1.64,1.82,1.82,2.16,2.18,1.96,2.50,2.16,...,4.82,5.00,6.28,5.32,5.10,5.72,5.66,6.14,6.00,6.16
1,Diet_A,1.56,1.52,1.90,1.92,2.08,2.34,2.00,2.50,2.12,...,5.20,6.18,5.52,5.32,5.54,5.60,5.64,6.08,5.86,6.20
2,Diet_A,1.54,1.20,1.44,1.68,1.94,1.82,1.88,2.06,1.96,...,4.24,5.18,5.56,5.38,5.54,5.38,5.38,6.04,6.18,6.14
3,Diet_B,1.18,1.62,1.88,1.64,1.96,2.80,2.46,3.14,2.10,...,5.14,5.00,5.24,5.62,5.38,5.86,5.68,6.22,6.26,6.46
4,Diet_B,1.18,1.40,1.78,1.88,2.00,1.92,1.58,2.10,2.10,...,5.08,5.32,5.36,5.06,5.12,5.36,5.34,6.18,6.74,6.88

In [3]:
# Renaming the heading where:
# Week_1 = Initial
# Week_2 = Final

all_data.rename(columns={'Week_1_Mean_Weight': 'Initial_Weight',
                     'Week_12_Mean_Weight': 'Final_Weight',
                     'Week_1_Mean_Length': 'Initial_Length',
                     'Week_12_Mean_Length': 'Final_Length'}, inplace = True)
all_data.head(5)

,Diets,Initial_Weight,Week_2_Mean_Weight,Week_3_Mean_Weight,Week_4_Mean_Weight,Week_5_Mean_Weight,Week_6_Mean_Weight,Week_7_Mean_Weight,Week_8_Mean_Weight,Week_9_Mean_Weight,...,Week_3_Mean_Length,Week_4_Mean_Length,Week_5_Mean_Length,Week_6_Mean_Length,Week_7_Mean_Length,Week_8_Mean_Length,Week_9_Mean_Length,Week_10_Mean_Length,Week_11_Mean_Length,Final_Length
0,Diet_A,1.50,1.64,1.82,1.82,2.16,2.18,1.96,2.50,2.16,...,4.82,5.00,6.28,5.32,5.10,5.72,5.66,6.14,6.00,6.16
1,Diet_A,1.56,1.52,1.90,1.92,2.08,2.34,2.00,2.50,2.12,...,5.20,6.18,5.52,5.32,5.54,5.60,5.64,6.08,5.86,6.20
2,Diet_A,1.54,1.20,1.44,1.68,1.94,1.82,1.88,2.06,1.96,...,4.24,5.18,5.56,5.38,5.54,5.38,5.38,6.04,6.18,6.14
3,Diet_B,1.18,1.62,1.88,1.64,1.96,2.80,2.46,3.14,2.10,...,5.14,5.00,5.24,5.62,5.38,5.86,5.68,6.22,6.26,6.46
4,Diet_B,1.18,1.40,1.78,1.88,2.00,1.92,1.58,2.10,2.10,...,5.08,5.32,5.36,5.06,5.12,5.36,5.34,6.18,6.74,6.88

In [4]:
# Drop all rows that have NaN/None Values

data = all_data.dropna()
data

,Diets,Initial_Weight,Week_2_Mean_Weight,Week_3_Mean_Weight,Week_4_Mean_Weight,Week_5_Mean_Weight,Week_6_Mean_Weight,Week_7_Mean_Weight,Week_8_Mean_Weight,Week_9_Mean_Weight,...,Week_3_Mean_Length,Week_4_Mean_Length,Week_5_Mean_Length,Week_6_Mean_Length,Week_7_Mean_Length,Week_8_Mean_Length,Week_9_Mean_Length,Week_10_Mean_Length,Week_11_Mean_Length,Final_Length
0,Diet_A,1.50,1.64,1.82,1.82,2.16,2.18,1.96,2.50,2.16,...,4.82,5.00,6.28,5.32,5.10,5.72,5.66,6.14,6.00,6.16
1,Diet_A,1.56,1.52,1.90,1.92,2.08,2.34,2.00,2.50,2.12,...,5.20,6.18,5.52,5.32,5.54,5.60,5.64,6.08,5.86,6.20
2,Diet_A,1.54,1.20,1.44,1.68,1.94,1.82,1.88,2.06,1.96,...,4.24,5.18,5.56,5.38,5.54,5.38,5.38,6.04,6.18,6.14
3,Diet_B,1.18,1.62,1.88,1.64,1.96,2.80,2.46,3.14,2.10,...,5.14,5.00,5.24,5.62,5.38,5.86,5.68,6.22,6.26,6.46
4,Diet_B,1.18,1.40,1.78,1.88,2.00,1.92,1.58,2.10,2.10,...,5.08,5.32,5.36,5.06,5.12,5.36,5.34,6.18,6.74,6.88
5,Diet_B,1.18,1.84,2.08,2.38,2.06,2.38,2.40,2.58,2.44,...,5.12,5.86,5.12,5.52,5.64,5.94,5.66,6.04,6.32,6.46
6,Diet_C,1.24,1.30,1.54,1.62,1.80,2.08,1.86,1.84,2.54,...,4.52,4.96,5.30,5.30,5.36,5.34,5.74,6.12,6.38,6.36
7,Diet_C,1.28,1.50,1.38,2.00,1.76,1.86,1.74,2.12,1.98,...,5.02,4.86,5.14,5.14,5.30,5.40,5.20,5.94,6.10,6.76
8,Diet_C,1.22,1.36,1.46,1.36,1.98,2.22,2.36,2.36,2.44,...,4.88,4.76,5.46,5.62,5.94,5.86,5.86,6.96,6.48,6.36
9,Diet_D,1.12,1.60,2.00,1.68,1.80,1.86,2.00,2.08,2.12,...,5.34,5.08,5.40,5.36,5.48,5.66,5.44,6.54,6.70,7.18
10,Diet_D,1.34,1.40,1.66,2.00,1.90,1.78,2.04,2.20,2.16,...,4.98,5.46,5.36,5.36,5.66,5.50,5.44,5.92,6.70,7.70
11,Diet_D,1.10,1.32,1.50,1.84,1.58,2.18,1.82,2.16,2.38,...,4.76,5.52,5.12,5.42,5.28,5.52,5.60,6.14,6.86,7.80
12,Diet_E,1.14,1.28,1.38,1.94,2.06,2.24,2.46,2.66,2.92,...,4.72,5.32,5.52,5.44,5.58,5.78,5.90,6.62,6.88,7.06
13,Diet_E,0.76,1.18,1.56,1.72,2.18,2.14,2.48,2.76,2.36,...,4.50,5.22,5.28,5.52,5.70,5.78,5.40,6.02,6.44,7.14
14,Diet_E,1.28,1.24,1.46,1.50,1.98,2.18,2.24,2.06,2.50,...,4.62,5.22,5.60,5.50,5.76,5.56,5.62,6.00,6.50,7.06

In [5]:
# extracting the initial and final values of the diets
new_data = data.filter(['Diets', 'Initial_Weight', 'Final_Weight', 'Initial_Length', 'Final_Length'])
new_data.head(5)

    Diets  Initial_Weight  Final_Weight  Initial_Length  Final_Length
0  Diet_A            1.50          3.08            4.14          6.16
1  Diet_A            1.56          2.98            4.40          6.20
2  Diet_A            1.54          3.06            4.41          6.14
3  Diet_B            1.18          3.18            4.46          6.46
4  Diet_B            1.18          3.10            4.14          6.88

In [35]:
#Describe data by group 
new_data.groupby('Diets').describe()

       Initial_Weight                                                    \
                count      mean       std   min   25%   50%   75%   max
Diets
Diet_A            3.0  1.533333  0.030551  1.50  1.52  1.54  1.55  1.56
Diet_B            3.0  1.180000  0.000000  1.18  1.18  1.18  1.18  1.18
Diet_C            3.0  1.246667  0.030551  1.22  1.23  1.24  1.26  1.28
Diet_D            3.0  1.186667  0.133167  1.10  1.11  1.12  1.23  1.34
Diet_E            3.0  1.060000  0.269072  0.76  0.95  1.14  1.21  1.28

       Final_Weight            ... Initial_Length       Final_Length  \
              count      mean  ...            75%   max        count
Diets                          ...
Diet_A          3.0  3.040000  ...          4.405  4.41          3.0
Diet_B          3.0  3.133333  ...          4.310  4.46          3.0
Diet_C          3.0  3.193333  ...          4.360  4.42          3.0
Diet_D          3.0  4.546667  ...          4.150  4.28          3.0
Diet_E          3.0  3.726667  ...          4.030  4.14          3.0


            mean       std   min   25%   50%   75%   max
Diets
Diet_A  6.166667  0.030551  6.14  6.15  6.16  6.18  6.20
Diet_B  6.600000  0.242487  6.46  6.46  6.46  6.67  6.88
Diet_C  6.493333  0.230940  6.36  6.36  6.36  6.56  6.76
Diet_D  7.560000  0.332866  7.18  7.44  7.70  7.75  7.80
Diet_E  7.086667  0.046188  7.06  7.06  7.06  7.10  7.14

[5 rows x 32 columns]

In [6]:
#Create a boxplot for the Mean_Weight

new_data.boxplot('Final_Weight', by='Diets', figsize=(12, 8))

Diet_A = new_data['Final_Weight'][new_data.Diets == 'Diet_A']

grps = pd.unique(new_data.Diets.values)
d_data = {grp:new_data['Final_Weight'][new_data.Diets == grp] for grp in grps}

k = len(pd.unique(new_data.Diets))  # number of conditions
N = len(new_data.values)  # conditions times participants
n = new_data.groupby('Diets').size()[0] #Participants in each condition

In [10]:
# ANOVA analysis for mean_weight using Statsmodels

# Import python packages

import statsmodels.api as sm
from statsmodels.formula.api import ols

# Set up the ANOVA model
mod = ols('Final_Weight ~ Diets', data = new_data).fit()

# Perform the ANOVA analysis
Weight_ANOVA = sm.stats.anova_lm(mod, typ=2)
print(Weight_ANOVA)

            sum_sq    df          F    PR(>F)
Diets     4.749173   4.0  26.021917  0.000029
Residual  0.456267  10.0        NaN       NaN

In [18]:
pair_t = mod.t_test_pairwise('Diets')
pair_t.result_frame

,coef,std err,t,P>|t|,Conf. Int. Low,Conf. Int. Upp.,pvalue-hs,reject-hs
Diet_B-Diet_A,0.093333,0.174407,0.535147,0.604244,-0.295270,0.481936,0.843377,False
Diet_C-Diet_A,0.153333,0.174407,0.879170,0.399942,-0.235270,0.541936,0.783937,False
Diet_D-Diet_A,1.506667,0.174407,8.638800,0.000006,1.118064,1.895270,0.000060,True
Diet_E-Diet_A,0.686667,0.174407,3.937152,0.002788,0.298064,1.075270,0.016610,True
Diet_C-Diet_B,0.060000,0.174407,0.344023,0.737953,-0.328603,0.448603,0.843377,False
Diet_D-Diet_B,1.413333,0.174407,8.103653,0.000011,1.024730,1.801936,0.000095,True
Diet_E-Diet_B,0.593333,0.174407,3.402005,0.006748,0.204730,0.981936,0.033289,True
Diet_D-Diet_C,1.353333,0.174407,7.759630,0.000015,0.964730,1.741936,0.000123,True
Diet_E-Diet_C,0.533333,0.174407,3.057982,0.012086,0.144730,0.921936,0.047475,True
Diet_E-Diet_D,-0.820000,0.174407,-4.701648,0.000839,-1.208603,-0.431397,0.005861,True